### ISSUE TITLE
demos/playbulb-candle/sw.js doesn't update cache

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/demos#13]
Cache is set at install time and updates to web site are not then re-cached.

**Comment by beaufortfrancois** [comment]
When I'll update some files, I was thinking about adding/updating a comment line to the service worker so that chrome knows it has changed.

``` js
// version: 2
```

**Comment by beaufortfrancois** [comment]
I guess we have to do it now because of https://github.com/WebBluetoothCG/demos/commit/ba364713597fe7713d32a5e2e6f1744873b72300
