### ISSUE TITLE
Device can't be found.

### ISSUE THREAD

**Issue by itsMattShull** [WebBluetoothCG/demos#15]
I got the airplane and set everything up, event with to the github demo page provided in the ReadMe, but my chromebook can't find the device.  I've updated chromeOS and made sure web bluetooth is on.  I'm able to pair with and play the bluetooth candle demo just fine.  I keep getting the error DOMException: User cancelled the requestDevice() chooser.

Any help?  Thanks!

**Comment by LeonNicholls** [comment]
Try the following to manually connect to the plane; first use Ctrl+Alt+T to open the Chrome Shell:
crosh> bt_console
[bluetooth]# scan on
Discovery started
...
[bluetooth]# scan off
Discovery stopped
[bluetooth]# connect 01:23:45:67:89:01

where 01:23:45:67:89:01 is the plane Bluetooth Low Energy address.

**Comment by itsMattShull** [comment]
How do I obtain the BLE address for the plane to confirm its correct?

**Comment by beaufortfrancois** [comment]
According to https://github.com/WebBluetoothCG/demos/blob/43f3af873c8f1192e960393aaf494bc543eacd38/bluetooth-toy-plane/index.html#L138, it looks like the Plane device contains a service whose UUID is `f000ffc0-0451-4000-b000-000000000000`.

Therefore, I would suggest you check for the service UUID, until you find the "good" one.

```
[bluetooth]# scan off
Discovery stopped
[bluetooth]# info 01:23:45:67:89:01
[bluetooth]# info 01:23:45:67:89:02
[bluetooth]# info 01:23:45:67:89:03
```

**Comment by beaufortfrancois** [comment]
Moreover, can you see the Plane device from an Android device with the https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp App?

**Comment by beaufortfrancois** [comment]
@derekshull Did you make it work eventually?

**Comment by beaufortfrancois** [comment]
Closing this issue. 
Feel free to reopen if you're still seeing this.
