### ISSUE TITLE
Demo for Eddystone configuration tool

### ISSUE THREAD

**Issue by JosefJezek** [WebBluetoothCG/demos#20]
Could you create demo for Eddystone configuration tool?

Like this service

https://github.com/ragingwind/node-eddystone-beacon-config

**Comment by g-ortuno** [comment]
On my TODO list, but @beaufortfrancois might get to it first.

**Comment by beaufortfrancois** [comment]
I'm not sure to understand there...

A Web "Eddystone-URL Configuration Service Tool" couldn't use Web Bluetooth API as it's only about acting as a central Role for now.

The only alternative I know is https://github.com/google/eddystone/tree/master/libraries/javascript/eddystone-advertising

Am I missing something?

**Comment by g-ortuno** [comment]
The [Eddystone Spec defines a service](https://github.com/google/eddystone/blob/master/eddystone-url/docs/config-service-spec.md) that can be used to configure a beacon. I think he wants a demo that interacts with that service i.e. a website that you can use to configure Eddystone Beacons. What he linked to is an implementation of the configuration service for node.

**Comment by JosefJezek** [comment]
@g-ortuno Yes :+1:

**Comment by beaufortfrancois** [comment]
Sorry for misunderstanding this ;)
I don't have a Eddystone-URL beacon next to me right now, but I've started to write what it could look like at https://github.com/beaufortfrancois/sandbox/blob/gh-pages/web-bluetooth/eddystone-url-config/index.html based on the spec.
You can have a look at https://beaufortfrancois.github.io/sandbox/web-bluetooth/eddystone-url-config/ in Chrome Beta and open JavaScript devtools to see if that works for you (assuming you have a beacon).

I'll update code and add UI as soon as I grab one beacon.

**Comment by JosefJezek** [comment]
Thank you :+1: 

I don't have Eddystone-URL beacon with Configuration Service now...

**Comment by JosefJezek** [comment]
Do you have any tip for good Eddystone-URL beacon with Configuration Service?

**Comment by beaufortfrancois** [comment]
Maybe @scottjenson can recommend some.

**Comment by scottjenson** [comment]
The early URIBeacons all had the service. We're working on V2 that works for all 3 frame types. It will be open source and we hope to offer lots of companies with that image. However, at this time, I don't know of any shipping beacons you can buy that supports the V1 standard.

**Comment by JosefJezek** [comment]
We have new Eddystone Configuration GATT Service
- https://github.com/google/eddystone/tree/master/configuration-service
- https://developers.googleblog.com/2016/04/growing-eddystone-with-ephemeral-identifiers.html

**Comment by ketile** [comment]
@JosefJezek You can buy a nRF52 Development Kit and program it with firmware from https://github.com/NordicSemiconductor/nrf5-sdk-for-eddystone in order to play around with the brand new Eddystone GATT Configuration Service. There's also an open source Android App linked in the repo that you may use and learn from. No JS library but a very flexible beacon platform to satisfy your Eddystone craving.

**Comment by JosefJezek** [comment]
@ketile Thank you

I would like create web app... ;-)

**Comment by beaufortfrancois** [comment]
I'm in the process of implementing one web app as well ;)

**Comment by ketile** [comment]
Looking forward to experimenting with your web app implementations :)

**Comment by beaufortfrancois** [comment]
For info, I'll focus on the eddystone URL frame type though.

**Comment by beaufortfrancois** [comment]
You can give a try to the infancy of the web app at https://beaufortfrancois.github.io/sandbox/web-bluetooth/eddystone-url-config/
Unlock/lock feature is not _yet_ implemented though.

**Comment by ketile** [comment]
The web app is not finding any beacons with the services you are scanning for. In our implementation, when the beacon goes into a connectable state, we are advertising the official Eddystone UUID of **0000FEAA-0000-1000-8000-00805F9B34FB**. The UUID of the connectable advertisement was a bit ambiguous in the original documentation and we have interpreted this differently than you. If you add this UUID to your filters list I can give it another try.

**Comment by beaufortfrancois** [comment]
According to a WIP Eddystone V2 beacon I have next to me, it advertises only `a3c87500-8ed3-4bdf-8a39-a01bebede295` UUID while in Config Mode ;(

```
Device F1:6F:DE:EC:F1:D6
        Name: ES G-SLOTS-X
        Alias: ES G-SLOTS-X
        Appearance: 0x0200
        Paired: no
        Trusted: no
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Vendor specific           (a3c87500-8ed3-4bdf-8a39-a01bebede295)
```

**Comment by beaufortfrancois** [comment]
@ketile Can you point to me the unclear documentation so that we fix it now?

**Comment by beaufortfrancois** [comment]
@scottjenson might know which UUID should be actually broadcasted while in Config Mode.

**Comment by scottjenson** [comment]
+roy want

He might be able to shed light on which UUID to use for configuration.

Scott

On Tue, Apr 19, 2016 at 7:22 AM, François Beaufort <notifications@github.com

**Comment by scottjenson** [comment]
If this is for the Eddystone beacon configuration, we put the Eddstone GATT
Service UUID in the configuration ADV packets  e.g. a3c87500
-8ed3-4bdf-8a39-a01bebede295

--Roy

On Tue, Apr 19, 2016 at 9:52 AM, Scott Jenson scott@jenson.org wrote:

> +roy want
> 
> He might be able to shed light on which UUID to use for configuration.
> 
> Scott
> 
> On Tue, Apr 19, 2016 at 7:22 AM, François Beaufort <
> notifications@github.com> wrote:
> 
> > @scottjenson https://github.com/scottjenson might know which UUID
> > should be actually broadcasted while in Config Mode.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/WebBluetoothCG/demos/issues/20#issuecomment-211942779

## 

---

_Roy Want_
Google Android
MTV-43-206P
Cell: 650 691 3600
www.roywant.com/cs

**Comment by ketile** [comment]
Thank you all for clearing this up. We will change our implementation to advertise the Eddystone GATT Service UUID when switching to configuration mode.

@beaufortfrancois To my knowledge the documentation I was referring to was never publicly available and was in draft form. Don't think there is a need to change it as it is now obsolete and replaced by the official [Eddystone Configuration Service specification](https://github.com/google/eddystone/tree/master/configuration-service).

**Comment by ketile** [comment]
@beaufortfrancois We changed [our implementation](https://github.com/NordicSemiconductor/nrf5-sdk-for-eddystone) to include the Eddystone GATT Service UUID in the scan response packet as recommended in the specification. Your web app successfully detects and connects to the beacon. Let me know when you have Unlock/Lock ready and I will try it out.

**Comment by beaufortfrancois** [comment]
@ketile Great!

The unlock/lock feature should work now BUT it looks like I can't read basic data such as the broadcasting URL, Radio Tx Power and the (Advanced) Advertised Tx Power without prompting user for the unlock key if the beacon is locked.

**Comment by scottjenson** [comment]
That was a security feature added as some felt that things like advertising
frequency and other values could be used to help identify the beacon. I
personally feel this is a bit overkill as you can observe all of these
values but nevertheless, this is working as intended.

Scott

On Tue, Apr 26, 2016 at 1:44 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
@ketile Can you have another look at https://beaufortfrancois.github.io/sandbox/web-bluetooth/eddystone-url-config/ and let me know if/when you will stumble upon issues ;)

**Comment by ketile** [comment]
@beaufortfrancois Just tried it again and was able to unlock the beacon :+1: After changing all the parameters the web app also successfully changed to the desired URL. 

Note that the `UPDATE` button is inactive unless I go to advanced settings and specify `Advertising Tx Power (dBm)`.

**Comment by beaufortfrancois** [comment]
The `Advertising Tx Power (dBm)`field  is required in the app. That's why the '`UPDATE` button is disabled.

May I ask why this field is not specified for the device?

**Comment by beaufortfrancois** [comment]
According to https://github.com/google/eddystone/tree/master/configuration-service

> If not set, the Tx power advertised in those frames shall be the value set in the Radio Tx Power characteristic, and the read value shall reflect that.

**Comment by beaufortfrancois** [comment]
Eddystone Beacon Configuration is now officially launched at http://cf.physical-web.org.
