### ISSUE TITLE
bluetooth-toy-plane blocked due to blacklisted service

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/demos#35]
bluetooth-toy-plane demo uses [`<platinum-bluetooth-device services-filter='["f000ffc0-0451-4000-b000-000000000000"]'`](https://github.com/WebBluetoothCG/demos/blob/2a9c5fbbf323760855b273e31a3df4eca7939091/bluetooth-toy-plane/index.html#L141) but that UUID is blacklisted as [# TI's Over-the-Air Download service](https://github.com/WebBluetoothCG/registries/blob/7b46fd5d58ea98fa098372a774fd7b981f0bdb0d/gatt_blacklist.txt#L20-21).

This results in the page showing the error dialog "Could not connect to bluetooth device!"

Possible actions:
- Does the toy advertize another UUID, or can we search by name instead? (I don't have a device)
- Take down demo.

**Comment by beaufortfrancois** [comment]
I will add an `optionalServicesFilter` attribute to https://github.com/PolymerElements/platinum-bluetooth and will update this demo so that @entertailion can review it.

**Comment by beaufortfrancois** [comment]
https://webbluetoothcg.github.io/demos/bluetooth-toy-plane/ has been updated.
