### ISSUE TITLE
Add ability to control intensity

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/demos#62]
I have a candle that I use for testing. Because it's usually on the battery runs out very fast. Could we add the ability to control the intensity so that the battery lasts longer?

@beaufortfrancois

**Comment by beaufortfrancois** [comment]
I thought it would be as simple as 
```js
let [saturation, red, green, blue] = [0xff, 0x00, 0xff, 0x00];
colorCharacteristic.writeValue(Uint8Array.of(saturation, red, green, blue));
```
but it isn't ;(

Do you have some thoughts on how we could map `rgb` values to control intensity?

**Comment by g-ortuno** [comment]
Does changing the saturation affect the intensity?

**Comment by beaufortfrancois** [comment]
It doesn't from what I've been testing sadly ;(
```js
// These look the same...
colorCharacteristic.writeValue(Uint8Array.of(0xff, 0x00, 0xff, 0x00));
colorCharacteristic.writeValue(Uint8Array.of(0x00, 0x00, 0xff, 0x00));

**Comment by g-ortuno** [comment]
:disappointed:
