### ISSUE TITLE
Printer not working

### ISSUE THREAD

**Issue by archimede2021** [WebBluetoothCG/demos#64]
Hi guys

Just tested Bluetooth demo with the printer and it doesn't work.

I have enabled chrome experimental web platform feature
. 
chrome://flags/#enable-experimental-web-platform-features

No device in list to pair when I tap print button.

Any advice?

Thank you

**Comment by beaufortfrancois** [comment]
Which OS did you test with?
Can you share logs? see https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs

**Comment by andersonprante** [comment]
Hello guys, first sorry my english.. I was very excited with the printer example, but does not work.

I am using Android 7.1.2.
When i click on button print, i select a printer on list, but nothing happens.
Debugging on chrome, i note that the code stop on "device.gatt.connect()".

* A print photo is attached
![img_20170701_212016](https://user-images.githubusercontent.com/15457836/27766404-cd356236-5ea4-11e7-8042-9137d48d0a3d.jpg)
![img_20170701_212028](https://user-images.githubusercontent.com/15457836/27766405-cd368378-5ea4-11e7-91dc-0ed67cb96fda.jpg)

Any advice? Thanks

**Comment by beaufortfrancois** [comment]
@entertailion may help

**Comment by LeonNicholls** [comment]
Unfortunately, I don't have the printer with me. You might want to try this on a different platform like a desktop or a chromebook to see if it makes any difference.

**Comment by andersonprante** [comment]
Hello guys, i forgot to comment, but I already tested with my notebook, but it also did not work...

**Comment by LeonNicholls** [comment]
On a chromebook it is possible to enable logging for the bluetooth stack and that might give a better idea of what is going wrong. You will have to use the command line console to do this while trying to connect to the device via the browser.

**Comment by scheib** [comment]
https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs has
tips for getting logs.

**Comment by andersonprante** [comment]
I'm tried view chrome://bluetooth-internals on google-chrome in android 7.1.2. Follows some screenshots... It seems to me that my printer is not compatible because GATT "never connect"
![imagem_montada](https://user-images.githubusercontent.com/15457836/29339827-7ef326b4-81f2-11e7-9536-7f6e182e3ed5.jpg)

**Comment by scheib** [comment]
Can https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en connect?

**Comment by g-ortuno** [comment]
The printer linked above does not support BLE (Bluetooth 4.0)[[1]](http://www.aliexpress.com/item/2Inch-Standby-Time-5-7-days-Android-Bluetooth-2-0-Wireless-Mobile-58mm-Mini-Thermal-Receipt/1398486616.html?s=p) it only supports Bluetooth 2.0. So it would not work with Web Bluetooth.

**Comment by andersonprante** [comment]
@scheib Yes connected
![resultado_programa](https://user-images.githubusercontent.com/15457836/29342195-c36979b2-81ff-11e7-8875-fa38b920233c.jpg)

**Comment by scheib** [comment]
g-ortuno@ has it right (but had a typo in comment, since it does not support BLE it "would not work with Web Bluetooth") (I'll edit the comment to correct it). nrf connect also shows that because after connecting you can see it doesn't have any printing services listed.

**Comment by andersonprante** [comment]
Thank's for all, I knew it that works only BLE devices. My printer support bluetooth 4.0 but not BLE, the solution i found, was to use a cordova plugin, and make a hybrid app.

**Comment by getgizmo** [comment]
Does this software only work with BLE devices? I have this same printer, and its got 4.0 support but not sure if the software has been updated to give it support.
