### ISSUE TITLE
Bluetooth.js + SBrick.js

### ISSUE THREAD

**Issue by 360fun** [WebBluetoothCG/demos#65]
If you like you can add my project too: http://sbrick.360fun.net/ ;)

**Comment by scheib** [comment]
Cool. ;) Submit a pull request to add the link you'd like? Would be great
if the landing page had a video of the demo as well to make it easy for
folks to understand who don't have an sbrick.

**Comment by 360fun** [comment]
I just did it! :D Since all the other projects links are from Github I thought to maintain the same style.

Right now I don't have an intro video but it's in the roadmap: I will update the Github page and also the official project page as soon as I have one! ;)
