### ISSUE TITLE
Add myo-web-bluetooth.js

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/demos#67]
https://github.com/charliegerard/myo-web-bluetooth.js
https://twitter.com/Charlie__Gerard/status/861325838217879552

**Comment by dineshvasan** [comment]
it not showing while scanning printer device in Chrome android mobile


This is for sample example  ( https://dineshvasan.github.io/test/)
 i have written for connecting bluetooth device for printing the text but it is not working. kindly check it whether i have made mistake in that code . kindly give me working solution for web bluetooth using service worker. i have referred  all the website but it not working properly.

As per my requirement to access the web bluetooth print the text using service worker.
Kindly do the Needful 
Printer Name : Epson
Printer Model : Epson TM-P20 
`
![20170821_153048](https://user-images.githubusercontent.com/31005845/29514442-2e1defba-8686-11e7-9b4a-e6a5a9b56b8e.jpg)

![20170821_153102](https://user-images.githubusercontent.com/31005845/29514448-359d6446-8686-11e7-814c-081c7fb40a03.jpg)
`

**Comment by scheib** [comment]
myo demo added in https://github.com/WebBluetoothCG/demos/commit/34c6ea082f677f8ff828cc47e0976cde8c8ec69c

The printer issue is duplicated here: https://github.com/WebBluetoothCG/demos/issues/69
