### ISSUE TITLE
 it not showing while scanning printer device in Chrome android mobile

### ISSUE THREAD

**Issue by dineshvasan** [WebBluetoothCG/demos#69]
it not showing while scanning printer device in Chrome android mobile

This is for sample example  ( https://dineshvasan.github.io/test/)
 i have written for connecting bluetooth device for printing the text but it is not working. kindly check it whether i have made mistake in that code . kindly give me working solution for web bluetooth using service worker. i have referred  all the website but it not working properly.

As per my requirement to access the web bluetooth print the text using service worker.
Kindly do the Needful 
Printer Name : Epson
Printer Model : Epson TM-P20 
`
![20170821_153048](https://user-images.githubusercontent.com/31005845/29514442-2e1defba-8686-11e7-9b4a-e6a5a9b56b8e.jpg)

![20170821_153102](https://user-images.githubusercontent.com/31005845/29514448-359d6446-8686-11e7-814c-081c7fb40a03.jpg)
`

**Comment by scheib** [comment]
https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs has good tips to get more information.

First, does this printer support Bluetooth Low Energy? On 
https://www.epson.de/en/products/sd/pos-printer/tm-p20-mobile-receipt-printer#specifications I see only "Bluetooth" listed. It's not clear.

Try chrome://bluetooth-internals page. Go to the "Devices" section, and then "Start Scan". Can you see the device? If yes, can you see services/characteristics?

If no, can you find and connect to the printer with [nRF Connect for Android](nRF Connect for Android)? Once connected, does it have services for printing?
