### ISSUE TITLE
playbulb demo does not find the playbulb

### ISSUE THREAD

**Issue by andreaskoler** [WebBluetoothCG/demos#70]
Hi!

I tried the playbulb demo on my android Smartphone with Chrome, but it does not find any ble devices.

I also tried the nRf Connect App and could find the playbulb and the corresponding UUIDs to change the color. So it seems that the problem is somewhere in the code of the demo. 

Any suggestions or ideas how to solve that?

Thank you!
Andreas

**Comment by scheib** [comment]
Thanks for taking a look.

https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs has several ideas.  After NRF Connect try chrome://bluetooth-internals and see if the device is listed there.

If the device is a newer or different model than the ones used to build a demo then the content of the advertisement packet may differ.  E.g. different UUIDs may be advertised.  Check the AD packet details in nrf connect and compare them to what is being filtered for by the web bluetooth app.

**Comment by scheib** [comment]
Looks like you're using
https://github.com/WebBluetoothCG/demos/tree/gh-pages/playbulb-candle and filed
an issue there <https://github.com/WebBluetoothCG/demos/issues/70>.  Let's
continue the discussion there
<https://github.com/WebBluetoothCG/demos/issues/70>.
