### ISSUE TITLE
How to find which is the service UUID

### ISSUE THREAD

**Issue by jordimc** [WebBluetoothCG/demos#75]
Hello,

I am having troubles on understanding from where you got the service UUID:
services: ['0000**18f0**-0000-1000-8000-00805f9b34fb']

As 0x18F0 is not listed on the https://www.bluetooth.com/specifications/assigned-numbers/service-discovery.

I would appreciate any thoughts on this.
Regards,

**Comment by beaufortfrancois** [comment]
@entertailion might know.

**Comment by LeonNicholls** [comment]
I can't remember exactly, but I did find some of these UUIDs from other open source projects. Some came from contacting the device manufacturers.

**Comment by jordimc** [comment]
Thanks for the answers. I am testing now with a NFC card reader and again the services and characteristics offered are not found in the list provided by bluetooth.com. It might be that my assumption is wrong or the specification is not being followed by the manufacturers.

**Comment by jyasskin** [comment]
The standardized services are listed in https://www.bluetooth.com/specifications/gatt/services, not the Service Discovery page, and their UUIDs are found by adding the "assigned number" to the top chunk of the "base UUID", 00000000-0000-1000-8000-00805F9B34FB. 0x18F0 is *not* assigned there, so the manufacturer is being naughty, but there's not much we can do about it.

**Comment by jordimc** [comment]
That makes sense. Thanks for the clarification @jyasskin!
