### ISSUE TITLE
How to change the font style?

### ISSUE THREAD

**Issue by evilman3624** [WebBluetoothCG/demos#77]
Can I adjust the font-style? Like bold, italic, underline, align-left and right, larger font size?

**Comment by nanjar** [comment]
same issue here. need to change the font style and image alignment. appreciated for any help

**Comment by Ce345** [comment]
All these characteristics are to be set in the styles.css file. You can learn about this file on various websites, like w3schools.

**Comment by scheib** [comment]
This repository is for demos for WebBluetooth.  This issue isn't clear which demo it is related to, though I'm guessing https://github.com/WebBluetoothCG/demos/tree/gh-pages/bluetooth-printer.  The purpose of the demos aren't to create full-featured applications, or to answer how to work with specific devices.  You can [contribute](https://github.com/WebBluetoothCG/demos/blob/gh-pages/bluetooth-printer/CONTRIBUTING.md) patches if you like.

I'll close this issue as it doesn't seem to be about the core Web Bluetooth demo functionality of the code.

**Comment by Ce345** [comment]
This  answer, question and closing could have been executed long ago.



Op di 30 mrt. 2021 02:30 schreef Vincent Scheib ***@***.***>:
