### ISSUE TITLE
heart-rate-sensor demo don't work with Miband

### ISSUE THREAD

**Issue by dj0001** [WebBluetoothCG/demos#79]
Miband can act as heart-rate-sensor: enable 3rd party HR access in Gadgetbridge (or MiFit)

I got it to work:
start an Activity on the band
first connect Gadgetbridge (maybe MiFit also works, untested)
then connect [web app](https://dj0001.github.io/miband3-selfie/csvtocanvas2.htm) in chrome android (click Scan button)

**Comment by scheib** [comment]
Thanks for the note.  If you'd like to add a link to the demo please submit a pull request to adding the demo link to https://github.com/WebBluetoothCG/demos/blob/gh-pages/README.md.  Ideally include a README in your demo page that shows the demo working for those without a device, similar to https://github.com/DeqingSun/BLE-Keyboard-Mouse-Dongle.
