### ISSUE TITLE
Playbulb Demo Not Working

### ISSUE THREAD

**Issue by itsMattShull** [WebBluetoothCG/demos#8]
I grabbed a playbulb candle and tried the demo here on github but I keep receiving that there are no bluetooth devices around.  I've tried it on my macbook and I've tried it on a nexus 7.  Are there any steps I'm missing to get the demo to work?

**Comment by beaufortfrancois** [comment]
You need a Chromebook or an Android M phone available at the codelab area.

**Comment by itsMattShull** [comment]
Yikes I'm in Arkansas watching remotely :-)  I have a chromebook though!  So even if I have web bluetooth enabled on the nexus 7 chrome browser and my macbooks chrome browser it won't work?

**Comment by itsMattShull** [comment]
Tried it on Chromebook and I get an error:

Uncaught TypeError: Cannot read property 'requestDevice' of undefined
connect @ playbulbCandle.js:25
(anonymous function) @ app.js:5

I believe it's referring to undefined being {filters:[{services:[ CANDLE_SERVICE_UUID]} ]}

**Comment by itsMattShull** [comment]
Turns out I had to restart the chromebook.  But now I get a "Argh! DOMException: Connection failed for unknown reason" error.  Any thoughts on what this might be?

**Comment by itsMattShull** [comment]
Good new everyone!  I refreshed the page and it connected.  It will change a color or do another action one time but whenever I try to do a second action it throws the error: "Uncaught (in promise) DOMException: GATT operation already in progress."

Going to dig around and see what I can find.  I'll post any updates if I have them.

**Comment by beaufortfrancois** [comment]
Hey Matt, you need your Chromebook in Dev Channel as there is a Bluez bug on Stable Channel where you can't write twice to the same characteristic.
https://support.google.com/chromebook/answer/1086915

**Comment by itsMattShull** [comment]
Awesome!  Thanks.

**Comment by itsMattShull** [comment]
I have an Android M Nexus 7, will it work on this device?  So far no go.

**Comment by beaufortfrancois** [comment]
It should yes. Do you use Chrome Dev Android app?
See https://plus.google.com/+FrancoisBeaufort/posts/HcLWbYiJkPG

**Comment by itsMattShull** [comment]
Ah, no I did not.  Thanks.
