### ISSUE TITLE
Dotti API 

### ISSUE THREAD

**Issue by LaBalaDeOro** [WebBluetoothCG/demos#87]
Hi! 

Thanks for the bluetooth-led-display Web Bluetooth demo. I recently bought a Dotti on eBay and was able to successfully use the code in the repo to connect to it. Great work! 👍

I'm creating this issue to ask for the API referenced at https://github.com/WebBluetoothCG/demos/blob/7b7397df596888b51043586a187a5b2e08f14ecd/bluetooth-led-display/index.html#L410

Before creating this Issue, I reached out to Witti Design to request the API doc over a month ago, and have heard nothing. I also looked for the doc at archive.org and it is unavailable there too. This is my last hope to obtain the API doc. Do you happen to have a copy of the doc? If so, would it be possible to commit it to the repo so I can reference it as I extended the demo?

Thanks!

Oro

**Comment by scheib** [comment]
Best wishes in your search for these docs. This sample code was contributed by Leon Nicholls who is unlikely to be monitoring these issues. There's no action we are able to take on this issue, so I'm closing. Happy tinkering.
